// BT question sets (Brief §6.3–6.5). One set per authored concept, spanning the four practice
// rungs to the per-concept floor (concept-check 3, guided 3, standard 3, stretch 1). BT concepts
// are theory, so items are recognition/judgement — no parameterized generators required — but
// every wrong option still encodes a diagnostic cause (Brief §6.5). Answerable from the concept's
// lesson alone (the sole-resource standard the 20-concept audit checks).

export const BT_ITEMS = [
  // ============================ BT-01 — types of business organisation ============================
  {
    id: 'BT-01-CC1', conceptIds: ['BT-01'], rung: 'concept-check', marks: 1,
    stem: 'Which type of business organisation is a separate legal person from its owners?',
    options: [
      { id: 'a', text: 'A limited liability company' },
      { id: 'b', text: 'A sole trader' },
      { id: 'c', text: 'A partnership' },
    ],
    answerId: 'a',
    distractors: { b: 'knowledge_gap', c: 'conceptual_misunderstanding' },
    rationale: 'Only a limited liability company is a separate legal person; a sole trader and a partnership are not.',
  },
  {
    id: 'BT-01-CC2', conceptIds: ['BT-01'], rung: 'concept-check', marks: 1,
    stem: 'A sole trader has unlimited liability. This means:',
    options: [
      { id: 'a', text: 'If the business owes more than it holds, the owner’s own assets can be taken to pay the debt' },
      { id: 'b', text: 'The owner can raise unlimited amounts of capital' },
      { id: 'c', text: 'The business can trade in any country without limit' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'Unlimited liability means the owner is personally liable for business debts — "down to her own mattress".',
  },
  {
    id: 'BT-01-CC3', conceptIds: ['BT-01'], rung: 'concept-check', marks: 1,
    stem: 'The "three Es" — economy, efficiency and effectiveness — are used to judge the success of:',
    options: [
      { id: 'a', text: 'A not-for-profit or public-sector body' },
      { id: 'b', text: 'A profit-orientated company, measured on profit' },
      { id: 'c', text: 'Only a sole trader' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'Value for money (the three Es) judges not-for-profit and public bodies; profit judges profit-orientated businesses.',
  },
  {
    id: 'BT-01-G1', conceptIds: ['BT-01'], rung: 'guided', marks: 1,
    stem: 'A county health clinic provides free care and exists to serve the community, not to make a profit. Which organisation type and success measure fit it?',
    options: [
      { id: 'a', text: 'Public-sector body — judged on value for money (the three Es)' },
      { id: 'b', text: 'Limited company — judged on profit' },
      { id: 'c', text: 'Sole trader — judged on the owner’s drawings' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['Ask first: what is the organisation FOR? Profit, or a service?', 'Purpose sets the measure: profit → profit; a public service → value for money (economy, efficiency, effectiveness).'],
    rationale: 'A clinic exists for a service, not profit → public-sector body judged on value for money.',
  },
  {
    id: 'BT-01-G2', conceptIds: ['BT-01'], rung: 'guided', marks: 1,
    stem: 'Wanjiku and her cousin pool their savings and skills to run one stall together, sharing profits, with neither protected from the stall’s debts. What have they formed?',
    options: [
      { id: 'a', text: 'A partnership' },
      { id: 'b', text: 'A limited liability company' },
      { id: 'c', text: 'A sole trader business with an employee' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    scaffold: ['Two or more owners sharing capital and profit points to one type.', 'Neither being protected from debts (unlimited liability) rules out a limited company.'],
    rationale: 'Two owners sharing capital, profit and unlimited liability is a partnership.',
  },
  {
    id: 'BT-01-G3', conceptIds: ['BT-01'], rung: 'guided', marks: 1,
    stem: 'Which single feature most clearly distinguishes a limited liability company from both a sole trader and a partnership?',
    options: [
      { id: 'a', text: 'Its owners can lose only what they invested, because it is a separate legal person' },
      { id: 'b', text: 'It is the only type that can employ staff' },
      { id: 'c', text: 'It is the only type that can make a profit' },
    ],
    answerId: 'a',
    distractors: { b: 'knowledge_gap', c: 'conceptual_misunderstanding' },
    scaffold: ['Separate legal personhood is the pivotal feature.', 'From it flows limited liability — owners risk only their investment.'],
    rationale: 'Separate legal personhood → limited liability is the defining contrast.',
  },
  {
    id: 'BT-01-S1', conceptIds: ['BT-01'], rung: 'standard', marks: 1,
    stem: 'Safaricom PLC is a public limited company. Which statement about how it is judged and who bears its losses is correct?',
    options: [
      { id: 'a', text: 'Judged on profit and shareholder return; shareholders risk only the amount they invested' },
      { id: 'b', text: 'Judged on value for money; shareholders are personally liable for its debts' },
      { id: 'c', text: 'Judged on profit; shareholders are personally liable for its debts' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'incorrect_treatment' },
    rationale: 'A profit-orientated company is judged on profit/return, and limited liability caps shareholders’ loss at their investment.',
  },
  {
    id: 'BT-01-S2', conceptIds: ['BT-01'], rung: 'standard', marks: 1,
    stem: 'A public agency spends KES 1m and treats 10,000 patients; a rival design would have treated 10,000 patients for KES 700,000. Which of the three Es does the KES 300,000 gap most directly concern?',
    options: [
      { id: 'a', text: 'Economy — obtaining the inputs more cheaply for the same output' },
      { id: 'b', text: 'Effectiveness — whether the objective was achieved' },
      { id: 'c', text: 'Profitability — the surplus left over' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'requirement_misread' },
    rationale: 'Same output (10,000 patients) at lower input cost is an economy question; effectiveness is about achieving the objective at all.',
  },
  {
    id: 'BT-01-S3', conceptIds: ['BT-01'], rung: 'standard', marks: 1,
    stem: 'Which statement is TRUE of a sole trader but FALSE of a limited liability company?',
    options: [
      { id: 'a', text: 'The owner is personally liable for the business’s debts' },
      { id: 'b', text: 'It exists to make a profit' },
      { id: 'c', text: 'It can be judged on value for money' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'Unlimited (personal) liability is the sole trader’s feature; a company’s owners have limited liability.',
  },
  {
    id: 'BT-01-ST1', conceptIds: ['BT-01'], rung: 'stretch', marks: 2,
    stem: 'A savings co-operative returns any surplus to its members rather than to outside shareholders, and exists to give members cheap credit. Applying only the lesson’s ideas, how is it best classified and judged?',
    options: [
      { id: 'a', text: 'Not-for-profit / mutual-benefit organisation — judged on how well it serves members (value for money), not on profit for outside owners' },
      { id: 'b', text: 'A limited liability company — judged purely on the profit it distributes to shareholders' },
      { id: 'c', text: 'A partnership of its members — judged on the drawings each member takes' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'transfer_failure' },
    rationale: 'A co-operative exists for member benefit, not profit for outside owners → a not-for-profit/mutual body judged on value for money.',
  },

  // ============================ BT-03 — stakeholders & classification ============================
  {
    id: 'BT-03-CC1', conceptIds: ['BT-03'], rung: 'concept-check', marks: 1,
    stem: 'A stakeholder is best defined as:',
    options: [
      { id: 'a', text: 'Anyone who affects, or is affected by, the organisation' },
      { id: 'b', text: 'Only the people who own shares in the organisation' },
      { id: 'c', text: 'Only the employees of the organisation' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'A stakeholder is anyone who affects or is affected by the organisation — far wider than shareholders or staff.',
  },
  {
    id: 'BT-03-CC2', conceptIds: ['BT-03'], rung: 'concept-check', marks: 1,
    stem: 'The lesson sorts stakeholders into exactly three groups. They are:',
    options: [
      { id: 'a', text: 'Internal, connected and external' },
      { id: 'b', text: 'Powerful, interested and neutral' },
      { id: 'c', text: 'Owners, managers and workers' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'The three classification groups are internal, connected and external.',
  },
  {
    id: 'BT-03-CC3', conceptIds: ['BT-03'], rung: 'concept-check', marks: 1,
    stem: 'A supplier who delivers goods to the business under a contract is which type of stakeholder?',
    options: [
      { id: 'a', text: 'Connected — tied to the business by a contract or investment' },
      { id: 'b', text: 'Internal — inside the business' },
      { id: 'c', text: 'External — outside, with no contractual tie' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Suppliers, customers, shareholders and lenders are connected — bound by contract or investment.',
  },
  {
    id: 'BT-03-G1', conceptIds: ['BT-03'], rung: 'guided', marks: 1,
    stem: 'Classify the Kenya Revenue Authority for Wanjiku’s stall: internal, connected or external?',
    options: [
      { id: 'a', text: 'External — a government body outside the business that still affects it' },
      { id: 'b', text: 'Connected — bound to the business by a contract' },
      { id: 'c', text: 'Internal — part of the business’s own staff' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['Is KRA inside the business, tied by a contract/investment, or neither?', 'Government and regulators sit outside with no contract → external.'],
    rationale: 'Government, KRA, the community and pressure groups are external stakeholders.',
  },
  {
    id: 'BT-03-G2', conceptIds: ['BT-03'], rung: 'guided', marks: 1,
    stem: 'Otieno is employed to run the stall day to day. Which group does he belong to, and what claim does he typically hold?',
    options: [
      { id: 'a', text: 'Internal — and as an employee he wants pay and job security' },
      { id: 'b', text: 'Connected — and he wants prompt payment of his invoices' },
      { id: 'c', text: 'External — and he wants tax and compliance' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['An employee sits inside the business.', 'Match the claim to the group: employees want pay and security.'],
    rationale: 'Employees are internal stakeholders whose claim is pay and security.',
  },
  {
    id: 'BT-03-G3', conceptIds: ['BT-03'], rung: 'guided', marks: 1,
    stem: 'Why does the lesson say the claims of different stakeholder groups "conflict"?',
    options: [
      { id: 'a', text: 'Because each group wants something different — e.g. customers want low prices while suppliers want prompt (costlier) payment' },
      { id: 'b', text: 'Because all stakeholders want exactly the same thing and compete for it' },
      { id: 'c', text: 'Because only external stakeholders ever have any claim at all' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    scaffold: ['List two groups’ claims from the lesson.', 'Notice they pull in opposite directions — that is the conflict.'],
    rationale: 'Different groups hold different, opposing claims (low prices vs prompt payment), which is why they conflict.',
  },
  {
    id: 'BT-03-S1', conceptIds: ['BT-03'], rung: 'standard', marks: 1,
    stem: 'Which list places each stakeholder in the correct group?',
    options: [
      { id: 'a', text: 'Internal: a manager. Connected: a lender. External: the local community.' },
      { id: 'b', text: 'Internal: a lender. Connected: the community. External: a manager.' },
      { id: 'c', text: 'Internal: a customer. Connected: a manager. External: a shareholder.' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Managers are internal; lenders (and customers, suppliers, shareholders) are connected; the community is external.',
  },
  {
    id: 'BT-03-S2', conceptIds: ['BT-03'], rung: 'standard', marks: 1,
    stem: 'A bank that lent Wanjiku the money for her fridge is which kind of stakeholder, and why?',
    options: [
      { id: 'a', text: 'Connected — a lender is tied to the business by its investment/loan' },
      { id: 'b', text: 'External — a bank is a government regulator of the business' },
      { id: 'c', text: 'Internal — the bank helps run the business day to day' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Lenders are connected stakeholders, bound by the loan they have made.',
  },
  {
    id: 'BT-03-S3', conceptIds: ['BT-03'], rung: 'standard', marks: 1,
    stem: 'Which statement about stakeholder classification is correct?',
    options: [
      { id: 'a', text: 'The owner herself is an internal stakeholder' },
      { id: 'b', text: 'Customers are external because they are not employees' },
      { id: 'c', text: 'A pressure group cannot be a stakeholder because it has no contract' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'The owner is internal; customers are connected (not external); a pressure group is an external stakeholder despite having no contract.',
  },
  {
    id: 'BT-03-ST1', conceptIds: ['BT-03'], rung: 'stretch', marks: 2,
    stem: 'A journalist who has never bought from the stall writes an article that could damage its reputation. Using only the lesson’s definition and groups, how should she be classified?',
    options: [
      { id: 'a', text: 'A stakeholder — she affects the business — and an external one, since she has no contract or investment tying her to it' },
      { id: 'b', text: 'Not a stakeholder at all, because she has never bought anything' },
      { id: 'c', text: 'A connected stakeholder, because writing about the stall is a form of contract with it' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'transfer_failure' },
    rationale: 'She affects the business (the definition), with no contractual tie → an external stakeholder.',
  },

  // ============================ BT-04 — Mendelow: power, interest, conflict ============================
  {
    id: 'BT-04-CC1', conceptIds: ['BT-04'], rung: 'concept-check', marks: 1,
    stem: 'Mendelow’s matrix maps each stakeholder on which two axes?',
    options: [
      { id: 'a', text: 'Power and interest' },
      { id: 'b', text: 'Profit and risk' },
      { id: 'c', text: 'Internal and external' },
    ],
    answerId: 'a',
    distractors: { b: 'knowledge_gap', c: 'conceptual_misunderstanding' },
    rationale: 'Mendelow maps power (can they force your hand?) against interest (do they care?).',
  },
  {
    id: 'BT-04-CC2', conceptIds: ['BT-04'], rung: 'concept-check', marks: 1,
    stem: 'A stakeholder with HIGH power and HIGH interest should be:',
    options: [
      { id: 'a', text: 'Managed closely — a key player' },
      { id: 'b', text: 'Given minimal effort' },
      { id: 'c', text: 'Kept informed only' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'High power + high interest = key player = manage closely.',
  },
  {
    id: 'BT-04-CC3', conceptIds: ['BT-04'], rung: 'concept-check', marks: 1,
    stem: 'According to the lesson, stakeholder conflict is resolved by:',
    options: [
      { id: 'a', text: 'Prioritising claims by power and interest, accepting that answering one disappoints another' },
      { id: 'b', text: 'Pleasing every stakeholder equally at the same time' },
      { id: 'c', text: 'Ignoring every stakeholder until the conflict passes' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'You prioritise by power and interest; you cannot please everyone at once — that trade-off IS stakeholder management.',
  },
  {
    id: 'BT-04-G1', conceptIds: ['BT-04'], rung: 'guided', marks: 1,
    stem: 'The Kenya Revenue Authority can close Wanjiku down and wants every sale taxed. Which quadrant and management approach?',
    options: [
      { id: 'a', text: 'High power, high interest → key player → manage closely, comply fully' },
      { id: 'b', text: 'High power, low interest → keep satisfied' },
      { id: 'c', text: 'Low power, high interest → keep informed' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['Rate power: can they force her hand? (Yes — they can close her.)', 'Rate interest: do they care about her sales? (Yes.) High/high → key player.'],
    rationale: 'KRA is high power and high interest → key player, managed closely.',
  },
  {
    id: 'BT-04-G2', conceptIds: ['BT-04'], rung: 'guided', marks: 1,
    stem: 'The sole soda distributor for her street has strong power over supply but little day-to-day interest in her particular stall. How should she manage him?',
    options: [
      { id: 'a', text: 'Keep satisfied — pay promptly to keep supply flowing' },
      { id: 'b', text: 'Minimal effort — a courtesy, no more' },
      { id: 'c', text: 'Keep informed — send regular updates but nothing else' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['High power, low interest is the key combination here.', 'That quadrant = keep satisfied.'],
    rationale: 'High power + low interest → keep satisfied (pay promptly to keep supply).',
  },
  {
    id: 'BT-04-G3', conceptIds: ['BT-04'], rung: 'guided', marks: 1,
    stem: 'One walk-up customer, one of hundreds, cares about price but cannot individually force Wanjiku’s hand. Which quadrant?',
    options: [
      { id: 'a', text: 'Low power, high interest → keep informed' },
      { id: 'b', text: 'High power, high interest → key player' },
      { id: 'c', text: 'Low power, low interest → minimal effort' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['One of hundreds → low power.', 'Cares about price → high interest. Low/high → keep informed.'],
    rationale: 'Low power + high interest → keep informed (fair prices, clear signage).',
  },
  {
    id: 'BT-04-S1', conceptIds: ['BT-04'], rung: 'standard', marks: 1,
    stem: 'Which pairing of quadrant and management response is INCORRECT?',
    options: [
      { id: 'a', text: 'High power, low interest → keep informed' },
      { id: 'b', text: 'Low power, low interest → minimal effort' },
      { id: 'c', text: 'High power, high interest → manage closely' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'High power, low interest → KEEP SATISFIED, not keep informed (that is the low-power/high-interest response).',
  },
  {
    id: 'BT-04-S2', conceptIds: ['BT-04'], rung: 'standard', marks: 1,
    stem: 'The same four stakeholders are re-examined for a DIFFERENT decision and some move quadrants. What does the lesson conclude from this?',
    options: [
      { id: 'a', text: 'The matrix is read per decision, not fixed once forever' },
      { id: 'b', text: 'The matrix must have been drawn wrongly the first time' },
      { id: 'c', text: 'Stakeholders never change quadrant once placed' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'The same names can sit in different quadrants for a different decision — the matrix is read per decision.',
  },
  {
    id: 'BT-04-S3', conceptIds: ['BT-04'], rung: 'standard', marks: 1,
    stem: 'A neighbour who dislikes the queue outside has neither power over the stall nor much interest in it. Managing her with "minimal effort" is an example of:',
    options: [
      { id: 'a', text: 'Setting management effort by the quadrant, and prioritising higher-power/higher-interest claims first' },
      { id: 'b', text: 'Ignoring a key player, which the matrix warns against' },
      { id: 'c', text: 'Treating interest as more important than power in every case' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Low power + low interest → minimal effort; effort is allocated by quadrant.',
  },
  {
    id: 'BT-04-ST1', conceptIds: ['BT-04'], rung: 'stretch', marks: 2,
    stem: 'A previously indifferent local politician suddenly campaigns on street trading before an election, gaining the power to change Wanjiku’s licence and taking a keen public interest. Using only Mendelow, what has changed and what should she now do?',
    options: [
      { id: 'a', text: 'He has moved into high power, high interest — she must now manage him closely as a key player, even though last month minimal effort was right' },
      { id: 'b', text: 'Nothing changes — once placed in minimal effort, a stakeholder stays there' },
      { id: 'c', text: 'She should keep him satisfied but need not treat him as a key player, since politicians never have real interest' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'transfer_failure' },
    rationale: 'Rising power and interest move him to the key-player quadrant; the matrix is re-read as circumstances change.',
  },

  // ============================ BT-05 — political and legal factors ============================
  {
    id: 'BT-05-CC1', conceptIds: ['BT-05'], rung: 'concept-check', marks: 1,
    stem: 'In the PESTEL scan, the "P" and the "L" stand for which two factors?',
    options: [
      { id: 'a', text: 'Political and legal' },
      { id: 'b', text: 'Price and location' },
      { id: 'c', text: 'Profit and liability' },
    ],
    answerId: 'a',
    distractors: { b: 'knowledge_gap', c: 'conceptual_misunderstanding' },
    rationale: 'P = political, L = legal — the parts of the environment set by the state and the law.',
  },
  {
    id: 'BT-05-CC2', conceptIds: ['BT-05'], rung: 'concept-check', marks: 1,
    stem: 'A government tax on sugary drinks is an example of which factor?',
    options: [
      { id: 'a', text: 'Political — it is fiscal policy set by government' },
      { id: 'b', text: 'Legal — it is a binding statute the business must obey' },
      { id: 'c', text: 'Neither — taxes are outside the PESTEL scan' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    rationale: 'Taxation and spending are fiscal policy — a political factor.',
  },
  {
    id: 'BT-05-CC3', conceptIds: ['BT-05'], rung: 'concept-check', marks: 1,
    stem: 'Which of these does the lesson list as a LEGAL factor?',
    options: [
      { id: 'a', text: 'Data-protection law' },
      { id: 'b', text: 'Trade tariffs' },
      { id: 'c', text: 'Political stability' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Data protection (with employment, health & safety, consumer and competition law) is a legal factor; tariffs and stability are political.',
  },
  {
    id: 'BT-05-G1', conceptIds: ['BT-05'], rung: 'guided', marks: 1,
    stem: 'A new minimum-wage law changes how Wanjiku must pay Otieno. Political or legal factor?',
    options: [
      { id: 'a', text: 'Legal — it is employment law, a binding rule of the game' },
      { id: 'b', text: 'Political — it is government spending policy' },
      { id: 'c', text: 'Neither — wages are an internal matter only' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'knowledge_gap' },
    scaffold: ['Is this the state acting (policy) or a binding statute the business must obey?', 'A statute governing how she pays staff is employment law → legal.'],
    rationale: 'A minimum-wage statute is employment law — a legal factor.',
  },
  {
    id: 'BT-05-G2', conceptIds: ['BT-05'], rung: 'guided', marks: 1,
    stem: 'The county introduces a new trading-licence regime that decides whether Wanjiku may trade at all. How does the lesson classify this?',
    options: [
      { id: 'a', text: 'Political (regulatory) — licensing imposed by a public authority' },
      { id: 'b', text: 'Legal — it is competition (anti-trust) law' },
      { id: 'c', text: 'Economic — it only affects her costs' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['Regulation and licensing by a public authority is one of the political factors listed.', 'It is not one of the named legal areas (employment, H&S, data, consumer, competition).'],
    rationale: 'The lesson classifies the county licence regime as political (regulatory).',
  },
  {
    id: 'BT-05-G3', conceptIds: ['BT-05'], rung: 'guided', marks: 1,
    stem: 'Why does the lesson say political and legal factors must be scanned even though Wanjiku "cannot vote either away"?',
    options: [
      { id: 'a', text: 'Because they are set outside the business yet still decide what she may sell and at what cost — ignore them and she plans for a world that no longer exists' },
      { id: 'b', text: 'Because she can lobby to remove any law she dislikes at any time' },
      { id: 'c', text: 'Because political and legal factors only ever help a business, never constrain it' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    scaffold: ['The factors are set by the state and the law, not by the business.', 'They bind the business regardless — so they must be planned around.'],
    rationale: 'Political and legal factors are external and binding; ignoring them means planning for a vanished world.',
  },
  {
    id: 'BT-05-S1', conceptIds: ['BT-05'], rung: 'standard', marks: 1,
    stem: 'Which set correctly separates political from legal factors?',
    options: [
      { id: 'a', text: 'Political: a fuel subsidy and an import ban. Legal: consumer-protection law and health & safety.' },
      { id: 'b', text: 'Political: health & safety and data protection. Legal: a sugar tax and trade tariffs.' },
      { id: 'c', text: 'Political: employment law. Legal: fiscal policy and political stability.' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Subsidies, trade rules and fiscal policy are political; consumer, H&S, employment and data-protection law are legal.',
  },
  {
    id: 'BT-05-S2', conceptIds: ['BT-05'], rung: 'standard', marks: 1,
    stem: 'The lesson says compliance with legal factors is "not optional". What does it call compliance instead?',
    options: [
      { id: 'a', text: 'A cost and a constraint the business plans around' },
      { id: 'b', text: 'A source of profit the business can rely on' },
      { id: 'c', text: 'An internal matter with no environmental dimension' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Compliance is a cost and a constraint planned around — breach carries penalties.',
  },
  {
    id: 'BT-05-S3', conceptIds: ['BT-05'], rung: 'standard', marks: 1,
    stem: 'A duty to keep customers’ data secure and a proposed tax on sugary drinks face the same stall. Which classifies BOTH correctly?',
    options: [
      { id: 'a', text: 'Data security = legal; sugar tax = political' },
      { id: 'b', text: 'Data security = political; sugar tax = legal' },
      { id: 'c', text: 'Both are legal factors' },
    ],
    answerId: 'a',
    distractors: { b: 'careless_slip', c: 'conceptual_misunderstanding' },
    rationale: 'Data protection is legal; a tax is fiscal policy, hence political.',
  },
  {
    id: 'BT-05-ST1', conceptIds: ['BT-05'], rung: 'stretch', marks: 2,
    stem: 'The government both raises import tariffs on soda (making stock costlier) and passes a new consumer-protection statute requiring clear price labels. Using only this lesson, classify each and say why they are grouped separately.',
    options: [
      { id: 'a', text: 'The tariff is political (a trade rule set by government); the labelling statute is legal (consumer-protection law) — one is the state acting through policy, the other a binding rule of the game' },
      { id: 'b', text: 'Both are legal, because both cost the business money' },
      { id: 'c', text: 'Both are political, because a government was involved in each' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'transfer_failure' },
    rationale: 'Tariffs are political (trade policy); consumer-protection statutes are legal — the split is policy versus binding law, not who was involved.',
  },

  // Examiner-report traps (FBT/FMA Sep 2024–Aug 2025). See src/content/examiner-insights.js.
  {
    id: 'BT-01-EX1', conceptIds: ['BT-01'], rung: 'standard', marks: 1,
    stem: 'A public hospital provides care free at the point of use. Which is a PROBLEM when measuring its performance? (1) it has multiple, often conflicting objectives; (2) the value of its outputs is hard to measure with no market price.',
    options: [
      { id: 'a', text: 'Both (1) and (2)' },
      { id: 'b', text: '(1) only' },
      { id: 'c', text: '(2) only' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Both are real problems — which is exactly why a not-for-profit body is judged on value for money (the three Es), not profit. Examiners report candidates picking only one. (FMA Sep24–Aug25 Ex6.)',
  },
  {
    id: 'BT-04-EX1', conceptIds: ['BT-04'], rung: 'standard', marks: 1,
    stem: 'Stefan buys 20% of Gad Co’s output but has many alternative suppliers and deliberately keeps them competing. From GAD CO’s point of view, where does Stefan sit on Mendelow’s matrix?',
    options: [
      { id: 'a', text: 'High power, low interest → keep satisfied' },
      { id: 'b', text: 'Low power, high interest → keep informed' },
      { id: 'c', text: 'High power, high interest → key player' },
    ],
    answerId: 'a',
    distractors: { b: 'conceptual_misunderstanding', c: 'conceptual_misunderstanding' },
    rationale: 'Because Stefan can switch away, he has HIGH power over Gad Co; being one of many suppliers to him, his interest in Gad Co is LOW → keep satisfied. Power/interest are judged from the stakeholder’s leverage, not their size. (BT Sep24–Aug25 Ex1.)',
  },
];

export default BT_ITEMS;
