// ledger.mjs — mechanically derive the build ledger for BUILD_STATUS.md (Execution Order §3).
// Every concept, its lesson state, its item counts by rung, its DONE verdict (lesson + question
// set), its sealed-pool count. No hand-count. Run: npm run ledger
// (paste the output into BUILD_STATUS.md's ledger section)

import { loadGraphFromSpec } from '../src/engine/node-loader.js';
import { LESSONS_BY_PAPER, hasLesson } from '../src/content/lessons/index.js';
import { itemsForConcept, conceptComplete, conceptQuestionReport } from '../src/content/items/index.js';

const graph = loadGraphFromSpec();
const out = (s = '') => process.stdout.write(s + '\n');

const PRACTICE = ['concept-check', 'guided', 'standard', 'stretch'];
function itemsFor(id) {
  const by = { 'concept-check': 0, guided: 0, standard: 0, stretch: 0, integrated: 0, sealed: 0, param: 0 };
  for (const it of itemsForConcept(id)) {
    if (by[it.rung] != null) by[it.rung] += 1;
    if (typeof it.generate === 'function') by.param += 1;
  }
  return by;
}

const PAPERS = ['BT', 'MA', 'FA'];
out('<!-- generated by `npm run ledger` — do not hand-edit -->');
out('');
let gDone = 0; let gTotal = 0; let gItems = 0;
for (const p of PAPERS) {
  const ids = graph.conceptsForPaper(p);
  const done = ids.filter(conceptComplete).length;
  const withLesson = ids.filter(hasLesson).length;
  let paperItems = 0;
  gDone += done; gTotal += ids.length;
  const rows = [];
  for (const id of ids) {
    const c = graph.get(id);
    const it = itemsFor(id);
    const items = PRACTICE.reduce((n, r) => n + it[r], 0) + it.integrated;
    paperItems += items;
    const doneMark = conceptComplete(id) ? '✓' : (hasLesson(id) ? '½' : '—');
    const set = hasLesson(id)
      ? `${it['concept-check']}/${it.guided}/${it.standard}/${it.stretch}${it.param ? ` +p${it.param}` : ''}`
      : '—';
    rows.push(`| ${id} | ${c.name} | ${hasLesson(id) ? '✓' : '—'} | ${set} | ${it.sealed} | ${doneMark} |`);
  }
  gItems += paperItems;
  out(`### ${p} — ${done} of ${ids.length} concepts DONE (${withLesson} have lessons) · ${paperItems} items · sealed 0`);
  out('');
  out('| concept | name | lesson | set cc/g/s/st | sealed | done |');
  out('|---|---|:--:|:--:|:--:|:--:|');
  for (const r of rows) out(r);
  out('');
}
out(`**Totals: ${gDone} of ${gTotal} concepts DONE (lesson + question set); ${gItems} practice items; 0 sealed.**`);
out('_"done" = ✓ (lesson + set to floor); ½ = lesson only, no complete set; — = neither. Parallel tracks, no priority (Order §4 A2)._');
