// ledger.mjs — mechanically derive the build ledger for BUILD_STATUS.md (Execution Order §3).
// Every concept, its lesson state, its item counts by rung, its sealed-pool count. No hand-count.
// Run: npm run ledger  (paste the output into BUILD_STATUS.md's ledger section)

import { loadGraphFromSpec } from '../src/engine/node-loader.js';
import { LESSONS_BY_PAPER, hasLesson } from '../src/content/lessons/index.js';

const graph = loadGraphFromSpec();
const out = (s = '') => process.stdout.write(s + '\n');

// Items don't exist yet; when they do, import the item bank here and count per concept/rung.
const itemsFor = () => ({ 'concept-check': 0, guided: 0, standard: 0, stretch: 0, integrated: 0, sealed: 0 });

const PAPERS = ['BT', 'MA', 'FA'];
out('<!-- generated by `npm run ledger` — do not hand-edit -->');
out('');
let gBuilt = 0; let gTotal = 0;
for (const p of PAPERS) {
  const ids = graph.conceptsForPaper(p);
  const built = ids.filter(hasLesson).length;
  gBuilt += built; gTotal += ids.length;
  out(`### ${p} — ${built} of ${ids.length} concepts have lessons · items 0 · sealed 0`);
  out('');
  out('| concept | name | lesson | items | sealed |');
  out('|---|---|:--:|:--:|:--:|');
  for (const id of ids) {
    const c = graph.get(id);
    const it = itemsFor(id);
    const items = it['concept-check'] + it.guided + it.standard + it.stretch + it.integrated;
    out(`| ${id} | ${c.name} | ${hasLesson(id) ? '✓' : '—'} | ${items} | ${it.sealed} |`);
  }
  out('');
}
out(`**Totals: ${gBuilt} of ${gTotal} concepts have lessons; 0 items; 0 sealed. Parallel tracks, no priority (Order §4 A2).**`);
